# Puerto
server:
  port: 8092

# Para ver la consola H2 en el navegador
# http://localhost:8091/h2-console
# Habilitando consola H2
spring:
  h2:
    console:
      enabled: true
# Ignorar config server
#  config:
#    import: "optional:configserver:"

# Deshabilitar config server
  cloud:
    config:
      enabled: false
      
# DB
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  sql:
    init:
      platform: h2
    
# JPA / HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
#        use_sql_comments: false
#        format_sql: false
    defer-datasource-initialization: true
        
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
